### ISSUE TITLE
Onlyoffice mobile ?

### ISSUE THREAD

**Issue by Blendman974** [ho1ger/awesomeNextcloudMobileApps#13]
OnlyOffice for android doesn't let you use nextcloud : you need onlyoffice portal on a server wich himself will sync to nextcloud :/

**Comment by severinkaelin** [comment]
I suppose this also applies to the iOS App. Since I don't have an iOS device at the moment, I can't confirm this. But I think it would be good if someone could check it, just to be sure.

**Comment by Blendman974** [comment]
Yes, the onlyoffice android apps can only links itself to onlyoffice portal and can't directly link itself to nextcloud.
