### ISSUE TITLE
DavDroid is also available for free

### ISSUE THREAD

**Issue by nickvergessen** [ho1ger/awesomeNextcloudMobileApps#6]
Not sure if you want to mention it, but davdroid is also available for free on f-droid.org
https://f-droid.org/de/packages/at.bitfire.davdroid/

Same for open tasks:
https://f-droid.org/de/packages/org.dmfs.tasks/

Btw the open tasks app uses caldav aswell. (caldav manages todos and calendar events)

**Comment by ho1ger** [comment]
I think mentioning these alternative markets is a good thing. If you like, just patch the file and I'll merge it into the existing document.

**Comment by ho1ger** [comment]
Added link to davdroid in f-droid market
